language: csharp
mono: none
dotnet: 2.1.402
script:
- dotnet test ./XUnitTest -c Release -f netcoreapp2.1
deploy:
  provider: heroku
  api_key:
    secure: JTL9VaJ8VcgaPW9/ZxO6M19wh2gQY7H+D4C8ngSdCaD+SQawbU1hqCIjioAI0Peb5sMxHAN8d3QIh6ZKYhWaEQM3R3opBGgnM11/1eeY75kFOmqBnAcQCw5FDcpJcKX4ToqnQRa4yvnBUD1ipLY5Dod9YvHCWnK0lZQoj9ZouGXefn6OiRwLrndI7rIH6Lbi84N8i0ySYyVNaJ535b7yxuxuExXTpzL66OVE50gOxbsJZPZR804HEfXRB11iuXFugJ9gLl5IqQsFaKXu7mRkGe0uphaPXOLA5nubRgiOTaCVGl5yGxvpFH4HJ18Cjmy0ViE7MXpCgBfh3NqZnZsX7UdZdpdwXbttfG6z+RFJ8jHaAitzYf6rQ8/6qLGcCXloZoHe+5hXIH8hGIC/sGEPiVPUi2CVfp9q0otuH1bFvRZEuZm/aSW3y7OdxfOl35uVWvowZrD8wi2HbBIUAiJ2Nd1TfkhHXjLY94X110eKSilH4myIaNMbexuriOO/Lv/4swNXmWJD1flA5YsuofuX6P17twfUUs0zndn5MkexA1GigDCYh4CnaCrqx5T++OnrweP8xEwFfM6dFgFM3MHvgww+Bpyb4QOLiwUBSexxEWP3fXkjsMenZXaW4Pye63nLU4M9aiNlflI6lTdXIo6E/2KnWrJVTNzDfxmhkDDZsWc=
  app: HelloWorldRSOI
  on:
    repo: sophieosipova/HelloWorldRSOI
